### ISSUE TITLE
request-promise -> fetch

### ISSUE THREAD

**Issue by derhuerst** [rastapasta/mapscii#1]
[`fetch`](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) (specifically [`fetch-ponyfill`](https://github.com/qubyte/fetch-ponyfill#fetch-ponyfill)) is a lot more lightweight than `request` and sufficient for 99% of the use cases.

would submit a PR if you don't mind.

**Comment by rastapasta** [comment]
would be a pleasure - thanks for the hint!
