### ISSUE TITLE
100% pure JavaScript! sunglasses

### ISSUE THREAD

**Issue by Noxmiles** [rastapasta/mapscii#100]
**Steps to reproduce**

Go to the github readme

**Current behavior**

It says: 100% pure JavaScript! sunglasses

**Expected behavior**

JavaScript is nothing cool. It should say: 100% pure JavaScript! *sad emoji*

**Comment by jaller94** [comment]
0. Why come to a free, open-source project for language bashing?
1. JavaScript works and powers many production systems.
2. There's a nice Telnet service, so no one has to execute any of the code.
3. This was added in the context of moving from CoffeeScript to vanilla JavaScript to have less maintenance on this open-source hobby project.
