### ISSUE TITLE
for the blind who made the map

### ISSUE THREAD

**Issue by hvsbloger** [rastapasta/mapscii#108]
for your kind information whoever made that map. look for the world map again , you cut the Jammu and Kashmir from the India map and included it to Pakistan and China. please do correct it

**Comment by rastapasta** [comment]
This is a geopolitical issue[1] MapSCII as an OSM[2] client can't address.
Additionally, MapSCII currently uses the latest available, outdated OSM2Vectortiles world tileset until an envisioned adaption to its successor OpenMapTiles is achieved.

[1] https://www.swp-berlin.org/publications/products/comments/2020C52_Kashmir.pdf
[2] https://www.openstreetmap.org/
