### ISSUE TITLE
load map points

### ISSUE THREAD

**Issue by pedroelbanquero** [rastapasta/mapscii#110]
any way to load map points ?

if no, can somebody tell me where in the source i can modify ?

**Comment by jaller94** [comment]
One would need to add features with `style.type === 'symbol'` to a tile's data or render a new layer.

The drawing functions are all in `Renderer.js`.
https://github.com/rastapasta/mapscii/blob/76f541db465e50755fbf1781c6d1b92f919b8edb/src/Renderer.js#L183

Closing as duplicate of #35 and #97.
