### ISSUE TITLE
mapscii message says renderer is busy 

### ISSUE THREAD

**Issue by plattyfish** [rastapasta/mapscii#121]
**Steps to reproduce**

**Expected behavior**

**Comment by plattyfish** [comment]
![Screenshot from 2022-09-25 20-45-34](https://user-images.githubusercontent.com/63901922/192162395-d7fa70be-5887-453e-a6fb-3beb2edea2cb.png)

**Comment by rastapasta** [comment]
Aloha @plattyfish - thanks for checking in, the MapSCII server has once again moved to another instance and was not yet priotized enough in the mitigation. Will be back online soon!

**Comment by rastapasta** [comment]
Ahoi @plattyfish, MapSCII's servers (web & telnet) are happily back up and running!

**Comment by markfswe** [comment]
@rastapasta Hi :) I encounter this issue

**Comment by rastapasta** [comment]
@ZerdoX-x not anymore i hope ;)
