### ISSUE TITLE
Connection time out

### ISSUE THREAD

**Issue by andrzejlisek** [rastapasta/mapscii#129]
I noticed, that connection into mapscii.me via telnet breaks after short time without pressing any key or moving mouse.

How to keep the connection for as long time as I want, without pressing keys or moving mouse?

I am using PuTTY on Windows and xterm on Linux. How to configure these terminals to avoid connection loss?

**Comment by rastapasta** [comment]
Aloha @andrzejlisek - the telnet session times out to allow as many people as possible to experience MapSCII.
Even though the server is pretty beefy, it's pretty loaded from time to time - especially during peak viral moments :) 

The easiest & independent way to avoid a timeout is by installing & running the MapSCII client locally (see Readme)
