### ISSUE TITLE
Scrambled map when wide characters are present

### ISSUE THREAD

**Issue by HarukaMa** [rastapasta/mapscii#13]
As the title says.

For example, zoom in at location 39.761, 116.424 (Beijing, China).

I have made sure that my terminal is showing wide characters in monospace (2 chars wide on Chinese characters for example).

**Comment by rastapasta** [comment]
Yey, well spotted - I removed the once implemented POI-to-emoji logic because of the same reason, just wasn't aware that the Chinese characters are wider as well. Will be tackled!

**Comment by Kuree** [comment]
Here is a screenshot of Shanghai.
![screenshot 2017-05-03 at 18 22 17](https://cloud.githubusercontent.com/assets/6099149/25684124/acb4ee96-302d-11e7-8818-a8eb65d87847.png)

**Comment by rastapasta** [comment]
@HarukaMa @Kuree pre-fix deployed to the telnet server, will be finished and pushed on the weekend, am incredibly busy with work atm. thanks for reporting in! will be solved with [string-width](https://github.com/sindresorhus/string-width)
