### ISSUE TITLE
Running 'telnet mapscii.me' not working?

### ISSUE THREAD

**Issue by testbughub** [rastapasta/mapscii#132]
Not sure if I'm missing anything, but when I run ```telnet mapscii.me``` in a terminal on Linux, 
it just prints;
```
$ telnet mapscii.me
Trying 144.76.97.34...
Connected to mapscii.me.
Escape character is '^]'.
```
and then nothing.

**Comment by Moffinguer** [comment]
Don't know if this problem is already solved, but at least, on this day, it's telling me the same message

**Comment by dogabudak** [comment]
Yeah, it is still and Issue. @rastapasta can you take a look ?

**Comment by dogabudak** [comment]
I think this one is fixed, i cant replicate it anymore. Can we close this ?

**Comment by Moffinguer** [comment]
Correct! It works again

**Comment by rastapasta** [comment]
Thanks for checking in, moved the telnet & tile server to another server again and made sure it is better monitored to avoid it going down again unnoticed :)
