### ISSUE TITLE
Ukraine is Missing from the Map

### ISSUE THREAD

**Issue by mrstephenhanson** [rastapasta/mapscii#138]
Ukraine is missing from the map. The borders are there and it renders, but the name of the country doesn't appear. This is the only country I've noticed this with. What's the deal?

**Comment by jaller94** [comment]
The Ukraine is included in the map.
It loads both on the Telnet and NodeJS version.

I guess you had some network issues.

![2024-08-28_11-53](https://github.com/user-attachments/assets/17823a6d-6eca-4460-84bc-0c2ba592ed18)

Note, the map data is several years old.
