### ISSUE TITLE
Can't connect to mapscii

### ISSUE THREAD

**Issue by PyramidalSociety** [rastapasta/mapscii#149]
After I ran the command "telnet mapscii.me" I got this message from the terminal

Trying 157.90.89.226...
telnet: connect to address 157.90.89.226: No route to host

Is the server down?

**Comment by NutmegCat** [comment]
I'm having the same issue

Fedora 40

**Comment by rastapasta** [comment]
@PyramidalSociety @NutmegCat thanks for checking in and sorry for letting you wait that long while being busy - migrated to new infrastructure once again, telnet server is up and running!
