### ISSUE TITLE
Feeling helpless...

### ISSUE THREAD

**Issue by hustcc** [rastapasta/mapscii#15]
:joy: feeling helpless.

![image](https://cloud.githubusercontent.com/assets/7856674/25701345/9b2baab2-30fe-11e7-9c0e-e8821f15147f.png)

**Comment by rastapasta** [comment]
😄 damn, would love to be able to fix this issue with code.

**Comment by hustcc** [comment]
Did you catch the point which make me helpless?

The issue can be fixed by update the map data :joy:

**Comment by derhuerst** [comment]
Are you referring to the fact that the label "Republic of China" is being shown next to the island of Taiwan?

**Comment by HarukaMa** [comment]
More of a political issue....

Just go ahead and edit the OSM data, as I don't think there is anything that can be done within this project...

**Comment by derhuerst** [comment]
> Just go ahead and edit the OSM data, as I don't think there is anything that can be done within this project...

First of all, there's plenty of discussion in the OSM community around politically debated borders & states, not only in China. Please make sure you comply with the conventions the OSM community has decided on, specifically with those [regarding PRC/ROC](https://help.openstreetmap.org/questions/47439/china-and-taiwan-names).

A long-term solution might be to do it like Google Maps does it: show different maps, depending on where you access them from.

**Comment by hustcc** [comment]
Sorry for this political issue.

**Comment by derhuerst** [comment]
I'm not asking you to apologise for this issue, just not to out-of-the-blue edit OpenStreetMap. 😉
