### ISSUE TITLE
OpenStreetMap License is ODbL, not CC-BY-SA

### ISSUE THREAD

**Issue by Robot8A** [rastapasta/mapscii#18]
They changed from CC-BY-SA a few years ago.

**Comment by rastapasta** [comment]
Humm, are you sure it applies to map tiles generated from OSM as well? The [Copyright and Licence](https://www.openstreetmap.org/copyright) page says:

> We require that you use the credit “© OpenStreetMap contributors”.
> You must also make it clear that the data is available under the Open Database Licence, and if using our map tiles, that the cartography is licensed as CC BY-SA. 

`mapscii` is using OSM vector map tiles, so my conclusion was CC BY-SA - please correct me if that's not the case.

**Comment by Piskvor** [comment]
The *data* is ODbL, quite unambiguously. What's CC-BY-SA is the map style in their tiles - that's not applicable here.

**Comment by rastapasta** [comment]
@Piskvor thanks for the clarification!
