### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by zaki1993** [rastapasta/mapscii#22]
It gives me a black screen on Ubuntu 16.04

**Comment by rastapasta** [comment]
Hey @zaki1993, thanks for checking in!

You're (most likely) using an old version of nodejs. Check with `node -v` if you are >= 4.5. If not, I recommend you using a node version manager like [n](https://github.com/tj/n) to upgrade.

Closing this issue for now and will reopen it in case it's not related to an old node version.

Cheers!

**Comment by zaki1993** [comment]
Hello, i updated to the version 7.10 and it still gives me black screen :(

**Comment by derhuerst** [comment]
Which version of Mapscii are you running? You can find out with `npm ls` or `npm ls -g`.

**Comment by zaki1993** [comment]
Im running 0.1.5 version.

**Comment by zaki1993** [comment]
It runs when i run it with telnet but when i try with mapscii it gives black screen then.
