### ISSUE TITLE
Mouse events are incorrectly processed in big terminals (>=96 columns)

### ISSUE THREAD

**Issue by smetana** [rastapasta/mapscii#24]
The problem is in term-mouse package
I have created pull request for it, but project is 5 years old and I am not sure if it is still alive.
https://github.com/CoderPuppy/term-mouse/pull/1

**Comment by smetana** [comment]
Fixed in term-mouse 0.2.0

**Comment by rastapasta** [comment]
Hey @smetana! Thanks for checking in and reporting the issue upstream - and sorry for my late reply, I'm in a kinda offline holiday at the moment 🌞  updated package.json and tested, all smooth and good to go! Cheers!
