### ISSUE TITLE
show coordinates at mouse position

### ISSUE THREAD

**Issue by derhuerst** [rastapasta/mapscii#4]
right now, `mapscii` shows something like "-66 40" at the bottom, i guess that's relative to the coordinates of the map center. what about showing the coordinates at the mouse position?

**Comment by rastapasta** [comment]
that's where i left when working on it last year, would love to - especially as this conversion is needed to make the drag+drop movement work again!

challenge here was the re-projection from mercator/console pixels to wgs84 - any idea/pr is welcome!

**Comment by derhuerst** [comment]
@juliuste

**Comment by juliuste** [comment]
Is [that](https://github.com/juliuste/projections) what you're looking for? (:

**Comment by rastapasta** [comment]
yeyyyy, got the algorithm figured out! 💃 coming soon!

**Comment by rastapasta** [comment]
Thanks for your pointing to `projections`, @juliuste ! 🍺 Was about to use it, until i figured out that I already dropped some sweat pearls back then for a mercator+zoom based calculation that i was able to reuse now.

Thanks again and enjoy the also freshly re-added drag+drop ;)
