### ISSUE TITLE
How can I activate mouse control in PuTTY?

### ISSUE THREAD

**Issue by silas229** [rastapasta/mapscii#40]
Does PuTTY support mouse events and how can I enable them?

**Comment by jaller94** [comment]
Putty does support mouse events and so does Mapscii via telnet.
The mouse support has to be turned on in Putty explicitly.

Try `:set mouse=a`. I found this tip here:
https://stackoverflow.com/questions/1865577/mapping-mouse-events-in-vim-through-putty-not-working
