### ISSUE TITLE
new Buffer(size) got deprecated

### ISSUE THREAD

**Issue by jaller94** [rastapasta/mapscii#42]
`new Buffer(size)` [got deprecated](https://nodejs.org/api/buffer.html#buffer_new_buffer_size), use `Buffer.alloc(size)` instead.

Places in the code: https://github.com/rastapasta/mapscii/blob/5873af5c96e24be0774a6471730bb11674835f21/src/BrailleBuffer.coffee#L44-L46

**Comment by jaller94** [comment]
`Buffer.alloc()` got introduced in NodeJS 5.10.0. I think it is reasonable to raise the required Node version to the latest LTS.

https://nodejs.org/api/buffer.html#buffer_class_method_buffer_alloc_size_fill_encoding

**Comment by derhuerst** [comment]
You could also just raise to `6`, which [is LTS and still being maintained](https://github.com/nodejs/Release#release-schedule). Some well-known npm lib authors have done this recently.

**Comment by jaller94** [comment]
Thanks for the mention of Node 6 which is still maintained until April of 2019.
Do you think it’s ok to require >= 6.14.0 as I did in #43?
There is still `--ignore-engine` for those those that wish to try earlier versions.

**Comment by derhuerst** [comment]
> Do you think it’s ok to require >= 6.14.0 as I did in #43?
> There is still `--ignore-engine` for those those that wish to try earlier versions.

Aside from the fact that you have no obligation to support *anything*, requiring the *latest* `6` version seems reasonable to me, as older versions have known security vulnerabilities.
