### ISSUE TITLE
Add new contributors to the LICENSE file

### ISSUE THREAD

**Issue by jaller94** [rastapasta/mapscii#52]
Since I started accepting pull requests the repository has gained a couple new contributors.
According to the chosen licence MIT contributors get attributed.

- [ ] I am in favour of a PR that adds their full names and/or GitHub nicknames (as `@name@github.com`) to the LICENCE file before the next release.

- [ ] If that is the way contributors get their attribution, it should get mentioned in a `Contributing.md`.
- [ ] And the repository should get a Pull Request template, asking with what name they would like to get attributed.

**Comment by derhuerst** [comment]
`Jannis R <mail@jannisr.de>`

**Comment by jaller94** [comment]
Resolved in 3dcebfa42e547bf86c945f9e80b06ea4011e0d86.
