### ISSUE TITLE
map not showing, timeout (snap and telnet)

### ISSUE THREAD

**Issue by NoeelMoeskops** [rastapasta/mapscii#65]
**Steps to reproduce**
1. `sudo snap install mapscii`
2. `mapscii`

OS: fedora 29
terminal: terminator (also tried konsole)
shell: zsh (also tried bash)

**Current behavior**

```
 mapscii
center: 52.512, 13.42   zoom: -0.17   mouse: 57.908, -149.212 { FetchError: request to http://mapscii.me/0/0/0.pbf failed, reason: connect ETIMEDOUT 185.162.249.146:80
    at ClientRequest.<anonymous> (/snap/mapscii/3/lib/node_modules/mapscii/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at Socket.socketErrorListener (_http_client.js:309:9)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at emitErrorNT (net.js:1281:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

  name: 'FetchError',
  message: 'request to http://mapscii.me/0/0/0.pbf failed, reason: connect ETIMEDOUT 185.162.249.146:80',
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT' }
center: -22.719, 71.841   zoom: -0.17   mouse: -63.713, 120.788
```

**Expected behavior**

A map being shown.

(On a side note `telnet mapscii.me` also doesn't work. Timeout trying to connect to 185.162.249.146)

**Comment by rastapasta** [comment]
Dear @NoeelMoeskops, thanks for checking in - the vector tile and telnet server will be back up tomorrow, its being moved from one data center to another and wasn't seen as critical.

Will keep this issue open until then - your patience is much appreciated :beer:

**Comment by NoeelMoeskops** [comment]
hmm, oke. wasn't the point of downloading mapscii that you wouldn't need to connect to a remote server in order for it to function?

**Comment by rastapasta** [comment]
mapscii tile server + telnet server back online - thanks again for your patience :)

it would work completely offline as long as you got the mbtiles (vector tiles container) offline as well - the osm2vectortiles ```planet.mbtiles``` is 54GB big - iirks!

running the client moves the whole processing & rendering to the client side - and by doing so allowing a much better experience with less delays (and less stress on my CPUs compared to telneting in xD).

tile server can be set @ [config.js](https://github.com/rastapasta/mapscii/blob/master/src/config.js#L6) and must to be able to respond to queries like ```/{z}/{x}/{y}``` with a vector tile.

cheers!

**Comment by rastapasta** [comment]
forgot to mention: ```source``` in the config can either be a http(s) or local path - so you don't need a tile server, just a local copy of the ```planet.mbtiles``` or any other vector tile container for full offline functionality.

**Comment by NoeelMoeskops** [comment]
Thanks for clearing things up!

**Comment by LWFlouisa** [comment]
Is there a way to specifically get the tiles? Map not showing up on local.

**Comment by rastapasta** [comment]
Hey @LWFlouisa, thanks for checking in - the server was down during a data center outage, all back and running again! :sparkles: :beers:

**Comment by rastapasta** [comment]
@LWFlouisa 
> Is there a way to specifically get the tiles?

Due to a [license dispute](https://github.com/osm2vectortiles/osm2vectortiles/issues/387) between @OSM2VectorTiles and @mapbox it is not possible to download the whole ```planet.mbtiles``` anymore.

There is an open ToDo to port MapSCII to its successor [OpenMapTiles](https://openmaptiles.org/) - see #9
