### ISSUE TITLE
How was the Telnet Setup?

### ISSUE THREAD

**Issue by jaredmichaelwilliams** [rastapasta/mapscii#76]
How did you setup this node application to work over telnet? There arent any instructions in the repo, issues or google

**Comment by rastapasta** [comment]
Aloha @jaredmichaelwilliams - wrote an own telnet server based on [node-telnet](https://github.com/TooTallNate/node-telnet), which gets clustererd via [pm2](https://pm2.keymetrics.io/). It also takes care a GeoIP lookup to center the map on the client's estimated location.

Can open source it as well as part of the current rewrite happening in the background.

**Comment by rastapasta** [comment]
Closing for now as no follow up question raised. Cheers!

**Comment by dervondenbergen** [comment]
Hey @rastapasta, altough this is an old issue, I would be interested in your telnet server solution/setup.
