### ISSUE TITLE
Where is Iran and Iraq

### ISSUE THREAD

**Issue by a-forghani-y79** [rastapasta/mapscii#81]
Hi
its very good idea and so funny
but i dont know where is Iran and Iraq
it has Tehran BUT hasnt IRAN? :|

**Comment by jaller94** [comment]
Both Iran and Iraq can be viewed without a problem.
In comparison to other countries, their names only appear when you're zoomed in a lot.

Especially for Iran, the renderer seems to favour lower-priority elements (capital names and roads) over the country label.

I was able to see the label of Iraq starting at zoom level 3.
![iraq](https://user-images.githubusercontent.com/10872136/76249765-4e596100-6244-11ea-9793-0e6c544e9ddd.png)

I was able to see the label of Iran starting at zoom level 5.
![iran](https://user-images.githubusercontent.com/10872136/76249664-21a54980-6244-11ea-9d5d-baae1be385ab.png)
