### ISSUE TITLE
user configurable config file

### ISSUE THREAD

**Issue by iandstanley** [rastapasta/mapscii#89]
**The problem**

creating config and cache directories in $HOME quickly ends up with a cluttered $HOME by the time you have several apps running

I would like to see an option to user define the data/cache directory used

**Proposed solution**

one newer solution is to check the environment to see if $XDG_CACHE_HOME is defined and if so create a subdirectory under it named after the app and put any cache data there

see

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Alternative solutions**

some developers solve it with an ENV variable pointing to the cache/data/config directories

others have a command line switch to define such a directory

**Additional context**

thanks for taking the time to read this

**Comment by derhuerst** [comment]
related: #60 

[`env-paths`](https://www.npmjs.com/package/env-paths) intends to help the Node.js ecosystem adhere to best practices.

**Comment by jaller94** [comment]
Sure, if `env-path` solves our troubles, I'm going to implement that tonight.

**Comment by jaller94** [comment]
Please have a look at #91 and tell me if this fixes your issue.
