### ISSUE TITLE
Mobile terminals support?  (android)

### ISSUE THREAD

**Issue by SoNickRND** [rastapasta/mapscii#98]
Just tried to connect to this wonderfull map from android telnet app, and ... half luck. :)

![image](https://user-images.githubusercontent.com/125238/106396965-29517c00-641c-11eb-8336-634baf8ab390.png)
Used this terminal app, didn't tried any other yet.
https://play.google.com/store/apps/details?id=mobiletelnet.feng.gao

Would like to help, but don't know how. ))

**Comment by jaller94** [comment]
You will need to use a monospace font. This will cause every character to have the same width.
If your terminal has the option to restrict the line width, that will fix this.

Mapscii already detects the line width of your terminal. If it overflows, that's usually an issue with the client.
